{
  "uid" : "dd905a4f6224f1cb",
  "name" : "TestClass.test_xfail",
  "title" : "Test xfail",
  "time" : {
    "start" : 1460636325263,
    "stop" : 1460636325275,
    "duration" : 12
  },
  "summary" : {
    "attachments" : 0,
    "steps" : 0
  },
  "failure" : {
    "message" : "",
    "stackTrace" : "self = <tests.test_xml.TestClass instance at 0x033EB378>\n\n    @pytest.mark.xfail()\n    def test_xfail(self):\n        'this test is an xfail'\n>       assert False\nE       assert False\n\ntests\\test_xml.py:24: AssertionError"
  },
  "description" : {
    "value" : "\nУ этого модуля, как и у его тестов, кириллические описания, данные в юникоде\n\nCreated on Oct 19, 2013\n\n@author: pupssman\n\r\nthis test is an xfail",
    "type" : "TEXT"
  },
  "severity" : "NORMAL",
  "status" : "PENDING",
  "testId" : null,
  "suite" : {
    "uid" : "78f28e191de4bf7",
    "name" : "tests.test_nonascii",
    "title" : "Test nonascii"
  },
  "steps" : [ ],
  "attachments" : [ ],
  "issues" : [ ],
  "labels" : [ {
    "name" : "thread",
    "value" : "10628-MainThread"
  }, {
    "name" : "suite-title",
    "value" : null
  }, {
    "name" : "suite-name",
    "value" : "tests.test_nonascii"
  }, {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "host",
    "value" : "ZinhVcoin-PC"
  } ],
  "parameters" : [ ]
}